development: &default
  adapter: postgresql
  database: clean-up-controller-app_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: clean-up-controller-app_test
